name: pyth_sui_dart
description: A Dart SDK for pyth sui service.
version: 1.0.2
repository: https://github.com/jovinlidan/pyth-sui-dart

environment:
  sdk: ^3.9.0

dependencies:
  sui_dart:
  bcs_dart: 0.1.2
  price_service_client: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
