name: pyth_sui_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  sui:
    git:
      url: https://github.com/jovinlidan/sui-dart.git
      ref: feat/bump-sui-sdk
  bcs:
    git:
      url: https://github.com/jovinlidan/bcs-dart.git
      ref: feat/bump-bcs-sdk
  price_service_client: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
